source 'https://rubygems.org'

gem 'activerecord-session_store'
gem 'ansi', '~> 1.5.0'
gem 'bootstrap', '~> 4.3.1'
gem 'coffee-rails'
gem 'countries', require: 'countries/global'
gem 'devise', '~> 4.7.1'
gem 'dotenv-rails'
gem 'font-awesome-rails'
gem 'httparty'
gem 'jbuilder'
gem 'jquery-rails'
gem 'mysql2', '~> 0.4.10'
gem 'newrelic_rpm'
gem 'nokogiri', '~> 1.13.5' 
gem 'omniauth'
gem 'omniauth-google-oauth2', '~> 0.6.0'
gem 'paper_trail'
gem 'paranoia'
gem 'puma'
gem 'rails', '7.0.3.1'
gem 'redis'
gem 'rotp'
gem 'rqrcode', '~> 0.10.1'
gem 'ruby-saml', '1.8.0'
gem 'saml_idp', git: 'https://github.com/gate-sso/saml_idp'
gem 'sass-rails'
gem 'sdoc', group: :doc
gem 'slim-rails'
gem 'turbolinks'
gem 'uglifier'
gem 'whenever', require: false

group :development, :test do
  gem 'capybara'
  gem 'coveralls'
  gem 'database_cleaner'
  gem 'dredd_hooks'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'mock_redis'
  gem 'pry'
  gem 'rails-controller-testing'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'shoulda-matchers'
  gem 'simplecov'
  gem 'simplecov-console'
  gem 'timecop'
  gem 'webmock'
end

group :development do
  gem 'web-console', platform: :ruby
end
