default: &default
  host: <%= ENV['CACHE_HOST'] %>
  port: <%= ENV['CACHE_PORT'] %>
  limit: 20

development:
  <<: *default

test:
  <<: *default

integration:
  <<: *default

production:
  <<: *default
