#!/bin/bash

set -e

if [[ $# -lt 1 ]]; then
  echo "$0 <user-name>"
  exit 1
fi

source vars

touch /etc/openvpn/keys/$1.ovpn

cat > /etc/openvpn/keys/$1.ovpn <<EOF
client
dev tun
proto udp
remote gate.gojek.co.id 1194
resolv-retry infinite
nobind
persist-key
persist-tun
ca ca.crt
cert $1.crt
key $1.key
comp-lzo
verb 3
auth-user-pass
auth-nocache
tun-mtu 1400
mssfix 1400
#Add your routes
route <<x.1.0.0 255.255.0.0>>
route <<x.4.0.0 255.255.0.0>>
EOF

./pkitool $1
cd /etc/openvpn/keys/ && tar zcf $1.tar.gz ca.crt $1.crt $1.key $1.ovpn
chmod 0600 $1.tar.gz

mkdir -p  /opt/vpnkeys/
cp $1.tar.gz /opt/vpnkeys/
rm $1.*
