#!/bin/bash

if [[ $# -lt 1 ]]; then
  echo "$0 <user-name>"
  exit 1
fi

cd /etc/openvpn/keys
cp /opt/vpnkeys/$1.tar.gz ./
tar -xf $1.tar.gz
rm $1.ovpn
touch $1.ovpn

cat > /etc/openvpn/keys/$1.ovpn <<EOF
client
dev tun
proto udp
remote <<your server name>> 1194
resolv-retry infinite
nobind
persist-key
persist-tun
ca ca.crt
cert $1.crt
key $1.key
comp-lzo
verb 3
auth-user-pass
auth-nocache
tun-mtu 1400
mssfix 1400

#add your routes here
route <<x.1.0.0 255.255.0.0>>
route <<x.2.0.0 255.255.0.0>>
EOF

tar zcf $1.tar.gz ca.crt $1.crt $1.key $1.ovpn
chmod 0600 $1.tar.gz

mkdir -p  /opt/vpnkeys/
cp $1.tar.gz /opt/vpnkeys/
rm $1.*
